#!/usr/bin/env bash

if [ -d "spec/dummy" ]; then
    rm -rf Gemfile.lock
fi

rbenv_version=$(rbenv version | awk '{print $1}')
rbenv gemset delete $rbenv_version $1 2> /dev/null

set -e

rbenv gemset create $rbenv_version $1
echo $1 >| .rbenv-gemsets
gem install bundler $2 $3
bundle install
rbenv rehash
