#!/usr/bin/env bash

set -Eeuo pipefail

usage() {
    cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS]

Access cheatsheet (cht.sh) with curl. Topic selection is done with fzf.

Options:
    -h      Print this help message and exit
EOF
    exit
}

say() {
    echo -e "### ${1-}" >&2
}

error() {
    say "ERROR: ${1-}"
}

die() {
    error "${1-}"
    exit "${2-1}"
}

parse_opts() {
    while getopts "h" optname; do
        case "${optname}" in
            h)
                usage
                ;;
            \?)
                die "Invalid option: ${OPTARG}"
                ;;
            :)
                die "Invalid option: ${OPTARG} requires an argument"
                ;;
            *)
                break
                ;;
        esac
    done
}

parse_opts "$@"
shift $((OPTIND - 1))

if ! command -v fzf &> /dev/null; then
    die "command not found: fzf"
fi

SELECTED=$(curl -s cht.sh/:list | fzf)

if test -z "${SELECTED}"; then
    exit
fi

curl -s "cht.sh/${SELECTED}?style=paraiso-dark" | ${PAGER:-less}
