#!/usr/bin/env python

import os.path
import subprocess
import sys

sys.path.append(os.path.join(os.environ['HOME'], 'lib'))

from pylocal import directories, git

if __name__ == '__main__':
    if git.check_dirty(directories.home(d) for d in directories.GIT_SUBDIRS):
        sys.exit(1)
