#!/usr/bin/env bash

set -e

found_dirty=false
thumbdrive_directory=/Volumes/thumbdrive

(
    for directory in $thumdrive_directory/pete/bin $thumdrive_directory/doc/* $thumdrive_directory/src/rcfiles $thumdrive_directory/src/personal/*; do

        if [[ -d $directory ]]; then
            echo ">>> Checking Git status of $directory"
            cd $directory

            if test $(git status -s 2> /dev/null | wc -l) -gt 0; then
                echo -n ">>> ..."
                echo -ne "\033[38;5;124m"
                echo -n "WARNING"
                echo -ne "\033[0m"
                echo ": repository is dirty"
                found_dirty=true
            fi

            echo
        fi
    done

    for directory in $HOME/bin $HOME/doc/* $HOME/src/rcfiles $HOME/src/personal/*; do
        if [[ -d $directory ]]; then
            echo ">>> Checking Git status of $directory"
            cd $directory

            if test $(git status -s --ignore-submodules=dirty 2> /dev/null | wc -l) -gt 0; then
                echo -n ">>> ..."
                echo -ne "\033[38;5;124m"
                echo -n "WARNING"
                echo -ne "\033[0m"
                echo ": repository is dirty"
                found_dirty=true
            fi

            echo
        fi
    done

    if [ "$found_dirty" = true ]; then
        echo -n ">>> "
        echo -ne "\033[38;5;124m"
        echo -n "ERROR"
        echo -ne "\033[0m"
        echo ": dirty Git repositories found"
        echo
        exit 1
    else
        exit 0
    fi
)
