#!/usr/bin/env bash

set -e
set -u

# Number of days starting today, counting backwards in which to do an analysis.
DAYS=7

# The `egrep -v` command won't work correctly with an empty string.
EXCLUSIONS="dummyexclusion"

LIST=0

AUTHOR=$(git config --get user.name)

usage() { echo "$(basename $0) [-d <days>] [-e <exclusions>]"; }

while getopts d:e:hl opt; do
    case $opt in
        d)
            DAYS=$OPTARG
            ;;
        e)
            EXCLUSIONS=$OPTARG
            ;;
        h)
            usage
            exit 0
            ;;
        l)
            LIST=1
            ;;
    esac
done

show_average_impact() {
    echo "Over $DAYS day(s), the average impact for <$AUTHOR> was:"

    # Calculate insertions.
    for n in $(jot $DAYS); do
        git log --author="$AUTHOR" --after="$n days ago" --before="$(expr $n - 1) days ago" --pretty=format: --shortstat
    done |
    egrep -v "$EXCLUSIONS" |
    perl -lne 'if (/(\d+)\s+insertion/) {$sum += $1; $n++} END {printf("\tinsertions:\t%.1f\n", $sum/$n)}'

    # Calculate deletions
    for n in $(jot $DAYS); do
        git log --author="$AUTHOR" --after="$n days ago" --before="$(expr $n - 1) days ago" --pretty=format: --shortstat
    done |
    egrep -v "$EXCLUSIONS" |
    perl -lne 'if (/(\d+)\s+deletion/) {$sum += $1; $n++} END {printf("\tdeletions:\t%.1f\n", $sum/$n)}'
}

list_impact() {
    for n in $(jot $DAYS); do
        git log --author="$AUTHOR" --after="$n days ago" --before="$(expr $n - 1) days ago" --pretty=format:"%h %ar" --shortstat
    done | sed '/^[[:space:]]*$/d'
}

if [[ $LIST -gt 0 ]]; then
    list_impact
else
    show_average_impact
fi
