#!/usr/bin/env bash

set -Eeuo pipefail

days=${1:-7}

usage() {
    cat << EOF
Usage: $(basename "$0") [-h] [num_days]

Get number of lines committed and deleted.

Available options:

-h, --help      Print this help and exit
num_days        Number of days ago to start from (default 7)
EOF
    exit
}

while getopts h opt; do
    case $opt in
    h)
        usage
        ;;
    *)
        echo "Invalid flag"
        exit 1
        ;;
    esac
done

author=$(git config --get user.name)
since_days_ago=$(date --date="${days} days ago" "+%Y-%m-%d")
since_yesterday=$(date --date="yesterday" "+%Y-%m-%d")

git log --author="${author}" --numstat --pretty="%H" --since "${since_yesterday}" |
    awk "
    NF==3 {
      plus += \$1;
      minus += \$2;
    }
    END {
      printf(\"Today:\t\t\t%d committed, %d deleted, %d net\n\", plus, minus, plus - minus)
    }
  "

git log --author="${author}" --numstat --pretty="%H" --since "${since_days_ago}" |
    awk "
    NF==3 {
      plus += \$1;
      minus += \$2;
    }
    END {
      printf(\"Over last ${days} day(s):\t%d committed per day\n\", plus / ${days})
    }
  "
