#!/usr/bin/env ruby

require 'English'
require 'etc'

def run_command(command)
  system "#{ command }"
  exit_status = $CHILD_STATUS.exitstatus

  unless exit_status.zero?
    warn "\n"
    warn ">>> ERROR: lint command failed => #{ command }"
    warn '>>> (To bypass this pre-commit hook, add `-n` to your Git command.)'
    warn "\n"
    exit exit_status
  end
end

def main
  pathnames = %x(git diff --cached --name-only --diff-filter=AM -z).split(?\x00)

  pathnames.each do |path|
    case File.basename(path)
    when /\.coffee/
      # FIXME: the following throws and error about multiple config files. Fix
      # it and replace the bare command below.
      #
      # config_fname = '.coffeelintrc'
      # home_config = File.join(Etc.getpwuid.dir, config_fname)
      # local_config = File.join('.', config_fname)

      # if File.exist?(local_config)
        # run_command "coffeelint -f #{ local_config } #{ path }"
      # elsif File.exist?(home_config)
        # run_command "coffeelint -f #{ home_config } #{ path }"
      # else
        # run_command "coffeelint #{ path }"
      # end

      run_command "coffeelint #{ path }"
    when /\.scss/
      config_fname = '.scss-lint.yml'
      home_config = File.join(Etc.getpwuid.dir, config_fname)
      local_config = File.join('.', config_fname)

      if File.exist?(local_config)
        run_command "scss-lint --config #{ local_config } #{ path }"
      elsif File.exist?(home_config)
        run_command "scss-lint --config #{ home_config } #{ path }"
      else
        run_command "scss-lint #{ path }"
      end
    when /\.css/
      run_command "csslint #{ path }"
    when /\.haml(?!.*spec)/
      run_command "haml-lint #{ path }"
    when /\.html(?!.*spec)/
      run_command "htmlhint #{ path }"
    when /\.js(?!.*spec)/i
      run_command "jshint #{ path }"
    when /\.rb/
      run_command "rubocop #{ path }"
    end
  end

  exit 0
end

main if $0 == __FILE__
