#!/usr/bin/env bash

set -e
set -u

echo ">>> htmlhint"
npm install -g htmlhint
echo

echo ">>> jshint"
npm install -g jshint
echo

echo ">>> csslint"
npm install -g csslint
echo

echo ">>> coffeelint"
npm install -g coffeelint
echo

echo ">>> complexity-report (cr)"
npm install -g complexity-report
echo

echo ">>> plato"
npm install -g plato
