#!/usr/bin/env bash

set -e
set -u

echo ">>> rubycritic"
gem install rubycritic
echo

echo ">>> rubocop"
gem install rubocop
echo

echo ">>> scss-lint"
gem install scss-lint
echo

echo ">>> haml-lint"
gem install haml-lint
echo

echo ">>> rails_best_practices"
gem install rails_best_practices
echo

echo ">>> brakeman"
gem install brakeman
echo

echo ">> Consider bullet, deadweight, rack-mini-profiler, and traceroute."
