#!/usr/bin/env bash

set -e
set -u

echo ">>> flay"
gem install flay
echo

echo ">>> flog"
gem install flog
echo

echo ">>> rubocop"
gem install rubocop
echo

echo ">>> turbulence"
gem install turbulence
echo

echo ">>> scss-lint"
gem install scss-lint
echo

echo ">>> haml-lint"
gem install haml-lint
echo
