#!/usr/bin/env bash

set -e
set -u

echo ">>> rubycritic"
gem install rubycritic
echo

echo ">>> rubocop"
gem install rubocop
echo

echo ">>> scss-lint"
gem install scss-lint
echo

echo ">>> haml-lint"
gem install haml-lint
echo

echo ">>> Consider also using:"
echo ">>>     bullet, brakeman, deadweight, rack-mini-profiler,"
echo ">>>     rails_best_practices, and traceroute."
