#!/usr/bin/env bash

set -e
set -u

echo "htmlhint"
npm install -g htmlhint

echo "jshint"
npm install -g jshint

echo "csslint"
npm install -g csslint

echo "complexity-report (cr)"
npm install -g complexity-report

echo ">> plato"
npm install -g plato
