#!/usr/bin/env bash

set -e
set -u

function change_name_back {
    if [[ -n "$TMUX" ]]; then
        tmux rename-window $original_window_name
    fi
}

trap change_name_back EXIT SIGINT

if [[ -n "$TMUX" ]]; then
    original_window_name=$(tmux list-windows | awk '/active/{print $2}' | tr -d '*')
    tmux rename-window $1
fi

mssh $1
