#!/usr/bin/env bash

set -e

(
    if [ ! -d "spec/dummy" ]; then
        cd ~/src/work/rewrite/apps_env/online_payroll
    fi

    echo ">>> Nuking test schema"
    bundle exec rake db:nuke_schema RAILS_ENV=test

    echo ">>> Nuking development schema"
    bundle exec rake db:nuke_schema
)
