#!/usr/bin/env bash

set -e

(
    echo ">>> cd ~/src/work/trampoline/online_auth"
    cd ~/src/work/trampoline/online_auth

    echo ">>> Nuking test schema"
    bundle exec rake db:nuke_schema RAILS_ENV=test

    echo ">>> Nuking development schema"
    bundle exec rake db:nuke_schema
)
