#!/usr/bin/env bash

HEURISTICS=$HOME/doc/computer/programming/red_green_refactor

# Open a project's todo file for editing.
if [[ -e $PWD/todo ]]; then
    TODO=$PWD/todo
elif [[ "$PWD" = "$HOME/src/personal/project" ]]; then
    TODO=$HOME/doc/project/todo
else
    TODO=$HOME/doc/work/todos/${PWD##*/}
fi

if [[ -e $HEURISTICS ]]; then
    $EDITOR -O $TODO $HEURISTICS
else
    $EDITOR -O $TODO
fi
