#!/usr/bin/env bash

usage() {
    cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS]

Pretty print path (PATH or MANPATH) environment variable.

Options:
    -h      Print this help message and exit
    -m      Print MANPATH (otherwise PATH)
EOF
    exit
}

say() {
    echo -e "### ${1-}" >&2
}

error() {
    say "ERROR: ${1-}"
}

die() {
    error "${1-}"
    exit "${2-1}"
}

PATH_TYPE="PATH"

parse_opts() {
    while getopts "hm" optname; do
        case "${optname}" in
            h)
                usage
                ;;
            m)
                PATH_TYPE="MANPATH"
                ;;
            \?)
                die "Invalid option: ${OPTARG}"
                ;;
            :)
                die "Invalid option: ${OPTARG} requires an argument"
                ;;
            *)
                break
                ;;
        esac
    done
}

parse_opts "$@"
shift $((OPTIND - 1))

printenv "${PATH_TYPE}" | tr ":" "\n"
