#!/usr/bin/env bash

set -e

ruby_version=$(rbenv version | awk '{print $1}');
project=$(basename $(pwd));

bundle show | \
    egrep -iv online | \
    ruby -ne 'puts "#{$1} #{$2}" if /\s+\*\s+(\S+)\s+\(([^\s)]+)/' | \
    while read gem version; do
        gem_file=${HOME}/.rbenv/versions/${ruby_version}/gemsets/${project}/cache/${gem}-${version}.gem;

        if [ ! -e "$gem_file" ]; then
            gem_file=${HOME}/.rbenv/versions/${ruby_version}/gemsets/global/cache/${gem}-${version}.gem;
        fi

        echo ">>> $gem $version => $gem_file";
        (
            # FIXME: uses version of Ruby with correct version of Rubygems
            # insalled for using push_gem.
            ruby19=$(rbenv versions | grep 1.9 | head -1 | awk '{print $1}')
            echo ">>> pushing with ruby version: $ruby19"
            eval "$(rbenv init -)"
            rbenv shell $ruby19
            push_gem $gem_file;
        )
        echo;
    done
