#!/usr/bin/env bash

set -e

ruby_version=$(rbenv version | awk '{print $1}');
ruby_small_version=${ruby_version//-p*/}
project=$(basename $(pwd));
ruby19=$(rbenv versions | grep 1.9 | head -1 | awk '{print $1}')

echo ">>> pushing with ruby version: $ruby19"
echo ">>> parsing bundled gems ..."
bundle show | \
    egrep -iv 'online|styleguide' | \
    ruby -ne 'puts "#{$1} #{$2}" if /\s+\*\s+(\S+)\s+\(([^\s)]+)/' | \
    while read gem version; do
        gem_file=${HOME}/.rbenv/versions/${ruby_version}/gemsets/${project}/cache/${gem}-${version}.gem;

        if [ ! -e "$gem_file" ]; then
            gem_file=${HOME}/.rbenv/versions/${ruby_version}/gemsets/global/cache/${gem}-${version}.gem;
        fi

        if [ ! -e "$gem_file" ]; then
            gem_file=${HOME}/.rbenv/versions/${ruby_version}/lib/ruby/gems/${ruby_small_version}/cache/${gem}-${version}.gem;
        fi

        if [ ! -e "$gem_file" ]; then
            echo ">>> searching for gem file: ${gem}-${version}.gem"
            gem_file=$(find ${HOME}/.rbenv -name ${gem}-${version}.gem | head -1)
        fi

        if [ ! -e "$gem_file" ]; then
            echo ">>> ERROR: gem file not found: ${gem}-${version}.gem"
        else
            echo ">>> pushing gem file: $gem_file";
            (
                eval "$(rbenv init -)"
                rbenv shell $ruby19
                push_gem $gem_file;
            )
        fi

        echo;
    done
