#!/usr/bin/env bash

if [ -z "$1" ]; then
    dir=$(pwd)
else
    dir=$1
fi

if [ ! -d "$dir" ]; then
    echo "ERROR: Invalid directory: $dir" 1>&2 
    exit 1
fi

if [ ! -n "$STY" ]; then
    echo "ERROR: No screen session found." 1>&2 
    exit 1
fi

cd $dir
screen -t edit vim
screen -t server
screen -t log tail -f log/development.log
