#!/usr/bin/env bash

set -e

(
    cd spec/dummy

    if bundle show pry-rescue >& /dev/null; then
        echo '>>> Starting with rescue'
        TRUSTED_IP=$(host $(hostname) | awk '{print $NF}') RAILS_ENV=test USE_SET_SCHEMA=true rescue rails server $*
    else
        TRUSTED_IP=$(host $(hostname) | awk '{print $NF}') RAILS_ENV=test USE_SET_SCHEMA=true rails server $*
    fi
)
