#!/bin/sh

userid=117931
domain=childrens
password=221bbst.

#desktop=10.34.4.94     # l4ap56; old
#desktop=10.221.65.160  # l4ap80; new wireless
desktop=10.34.4.104     # l4ap80; new lan

rdp_ok_code=0
rdp_window_closed_code=2

echo $password | /usr/bin/rdesktop -p - -u $userid -d $domain -g 1280x800 -P $desktop 

code=$?

if [ $code != $rdp_ok_code -a $code != $rdp_window_closed_code ]; then
    /usr/bin/xmessage "rdesktop failed" &
fi
