#!/bin/sh

userid=su117931
domain=childrens
password='.oO(hmm)'

server=10.200.20.22

rdp_ok_code=0
rdp_window_closed_code=2

echo $password | /usr/bin/rdesktop -K -p - -u $userid -d $domain -g 1280x800 -P $server

code=$?

if [ $code != $rdp_ok_code -a $code != $rdp_window_closed_code ]; then
    /usr/bin/xmessage "rdesktop failed" &
fi
