#!/usr/bin/env bash

# Overwrite file, but muiltiply number in first column by 0.75.

set -e

if [[ $# -lt 1 ]]; then
    echo "### ERROR: no file name provided" >&2
    exit 1
fi

awk -i inplace 'NF { $1 = sprintf("%d", $1 * 0.75) } 1' "$1"
