#!/usr/bin/env ruby

def die(msg)
  warn "#{ File.basename($0) }: ERROR: #{ msg }"
  exit 1
end

def main
  file_name, line_number = ARGV
  die 'no file name given' unless file_name
  line_number_spec = (line_number ? ":#{ line_number }": '')

  case file_name
  when /spec\.rb$/
    exec "bundle exec rspec -f d #{ file_name }" + line_number_spec
  when /spec(\.js|\.js\.coffee|\.coffee)$/i
    if File.exist?('./lib/tasks/karma.rake')
      exec 'bundle exec rake app:karma:run'
    elsif File.exist?('./spec/dummy/spec/teaspoon_env.rb')
      exec "bundle exec teaspoon --fail-fast -r spec/dummy/spec/teaspoon_env.rb #{ file_name }"
    else
      die "can't figure out JavaScript test runner: #{ file_name }"
    end
  when /test\.rb$/
    exec "bundle exec rake test TEST=#{ file_name }"
  when /\.feature$/
    exec "SELENIUM_DRIVER=true bundle exec cucumber -r features #{ file_name }" + line_number_spec
  else
    die "unrecognized file name: #{ file_name }"
  end
end

main if $0 == __FILE__
