#!/usr/bin/env bash

# This code is only for reference as it should probably be sourced inside a
# Bash config file.

if [ -r ~/.ssh-agent ]; then
    source ~/.ssh-agent >/dev/null
else
    echo "### Starting SSH agent."

    if command -v killall 1>/dev/null 2>&1; then
        killall -q ssh-agent
    fi

    (umask 066; ssh-agent >| ~/.ssh-agent)
    source ~/.ssh-agent >/dev/null
fi

ssh-add -l &>/dev/null
if [ "$?" == 2 ]; then
    echo "### Starting SSH agent."

    if command -v killall 1>/dev/null 2>&1; then
        killall -q ssh-agent
    fi

    (umask 066; ssh-agent >| ~/.ssh-agent)
    source ~/.ssh-agent >/dev/null
fi

ssh-add -l &>/dev/null
if [ "$?" == 1 ]; then
    echo "### Adding SSH keys to SSH agent."

    if [ $(ls ~/.ssh/id_*.pub | wc -l) -gt 0 ]; then
        ssh-add $(ls ~/.ssh/id_* | grep -v '\.pub')
    fi
fi

