#!/usr/bin/env bash

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "*** ERROR: no remote SSH target provided (user@host)" >&2
    exit 1
else
    HOST=$1
fi

SOURCE_DIR=${HOME}/src/personal/remote/dotfiles

ssh "${HOST}" "rm -f ~/.bash_profile"
scp "${SOURCE_DIR}/bash_profile" "${HOST}:~/.bash_profile"
ssh "${HOST}" "rm -f ~/.bashrc"
scp "${SOURCE_DIR}/bashrc" "${HOST}:~/.bashrc"
ssh "${HOST}" "rm -f ~/.editrc"
scp "${SOURCE_DIR}/editrc" "${HOST}:~/.editrc"
ssh "${HOST}" "rm -f ~/.git-prompt.sh"
scp "${SOURCE_DIR}/git-prompt.sh" "${HOST}:~/.git-prompt.sh"
ssh "${HOST}" "rm -f ~/.inputrc"
scp "${SOURCE_DIR}/inputrc" "${HOST}:~/.inputrc"
ssh "${HOST}" "rm -f ~/.tmux.conf"
scp "${SOURCE_DIR}/tmux.conf" "${HOST}:~/.tmux.conf"
ssh "${HOST}" "rm -f ~/.vimrc"
scp "${SOURCE_DIR}/vimrc" "${HOST}:~/.vimrc"
ssh "${HOST}" "rm -rf ~/.vim"
scp -r "${SOURCE_DIR}/vim" "${HOST}:~/.vim"
