#!/usr/bin/env bash

set -euo pipefail

rm -f "${HOME}/.ssh-agent"
ssh-agent > "${HOME}/.ssh-agent"
source "${HOME}/.ssh-agent"
ssh-add -D
ssh-add $(find -L "${HOME}/.ssh" -name "id_*" -type f | grep -Ev "\.pub$")
