#!/usr/bin/env bash

set -e

if [ -z "$TMUX" ]; then
    >&2 echo "ERROR: not executed inside tmux."
    exit 1
fi

original_window_name=$(tmux list-windows | awk '/active/{print $2}' | tr -d '*')
trap "tmux rename-window $original_window_name" EXIT
tmux rename-window $1
ssh $1
