#!/usr/bin/env bash

set -e

if [ -z "$TMUX" ]; then
    tmux_new_session general
fi

original_window_name=$(tmux list-windows | awk '/active/{print $2}' | tr -d '*')
trap "tmux rename-window $original_window_name" EXIT
tmux rename-window $1
ssh $1
