#!/usr/bin/env bash

set -o errexit

if [ $# -lt 1 ]; then
    echo "ERROR: not enough arguments" 1>&2
    echo "usage: $(basename $0) session_name" 1>&2
    exit 1
fi

session_name=$1
directory="${HOME}/src/${session_name}"

test -d $directory || { echo "ERROR: no directory: $directory" 1>&2; exit 1; }

tmux new-session -ds $session_name
tmux new-window -n "editor" -t $session_name "cd $directory && bash"
tmux kill-window -t $session_name:0
tmux move-window -s 1 -t 0
tmux new-window -n "shell" -t $session_name "cd $directory && bash"
tmux select-window -t $session_name
tmux attach-session -t $session_name
