#!/usr/bin/env perl

# This program takes its stdin, writes it to a temp file, exectues its
# arguments as a command with the filename of the temp file appended, and then
# deletes the temp file. This allows one to pass stdin to commands that only
# read from a file and don't accept stdin.

use warnings;
use strict;
use File::Basename;

my $fname = "/tmp/" . basename($0) . ".$$";
open(TMP, "+>", $fname) or die "failed open of $fname : $!";

while (<STDIN>) {
    print(TMP $_);
}

close TMP;
push @ARGV, $fname;
system(@ARGV) == 0 or die "failed system(): $!";
unlink $fname;
