#!/usr/bin/env bash

set -e

if [[ $# -ne 1 ]] ; then
    echo "Error: you must specify one and only one Git branch."
    exit 1
fi

if [ -r "Gemfile" ]; then
    egrep -i online Gemfile | \
        egrep -i path  | \
        perl -lne "print \$1 if /path: \'(.*)\'/" | \
        tr /A-Z/ /a-z/ | \
        while read dir; do
            echo ">>> $dir"
            (
                cd $dir
                git checkout $1
                git pull
            )
            echo
        done
fi
