#!/usr/bin/env bash

set -e

echo ">>> Bundling gems"

bundle

echo ">>> Pulling Git projects"
(
    cd ..
    git_pull_list
)

echo ">>> Nuking test schema"
bundle exec rake db:nuke_schema RAILS_ENV=test

echo ">>> Nuking development schema"
bundle exec rake db:nuke_schema

echo ">>> Setting up test DB"
if [ -d "spec/dummy" ]; then
    bundle exec setup_test_db
else
    bundle exec rake db:test:prepare
fi
