#!/usr/bin/env bash

set -e

if [ -d "spec/dummy" ]; then
    echo ">>> Building rbenv gemset"
    build_rbenv_gemset $(basename $(pwd))
else
    echo ">>> Bundling gems"
    bundle
fi

echo ">>> Pulling Git projects"
(
    cd ..
    git_pull_list
)

nuke_schemas

echo ">>> Setting up test DB"
if [ -d "spec/dummy" ]; then
    bundle exec setup_test_db
else
    bundle exec rake db:test:prepare
fi
