#!/usr/bin/env bash

userid="117931"
domain="childrens"

#desktop=10.34.4.94     # l4ap56; old
#desktop=10.221.65.160  # l4ap80; new wireless
desktop=10.34.4.104     # l4ap80; new lan

rdp_port=3389
ssh_portal=riverstyx.thechildrenshospital.org
ssh_portal_port=5280
rdp_ok=0
rdp_window_closed=2

keychain ~/.ssh/id_dsa
source ~/.keychain/$(hostname)-sh

/usr/bin/ssh -TNCL ${rdp_port}:${desktop}:${rdp_port} \
    -p $ssh_portal_port -l is${userid} $ssh_portal &

tunnel_pid=$!
sleep 5

if [ $? != 0 ]; then
    /usr/bin/xmessage "ssh tunnel failed" &
    /bin/kill -9 $tunnel_pid
    exit 1
fi

/usr/bin/rdesktop -d $domain -u $userid -Pg 1280x800 localhost

if [ $? != $rdp_ok -a $? != $rdp_window_closed ]; then
    /usr/bin/xmessage "rdesktop failed" &
fi

/bin/kill -9 $tunnel_pid
