#!/usr/bin/env bash

userid="117931"
domain="childrens"

#desktop=10.34.4.94     # l4ap56; old
#desktop=10.221.65.160  # l4ap80; new wireless
desktop=10.34.4.104     # l4ap80; new lan

rdp_port=3389
ssh_portal=riverstyx.thechildrenshospital.org
ssh_portal_port=5280
rdp_ok=0
rdp_window_closed=2

keychain ~/.ssh/id_dsa
source ~/.keychain/$(hostname)-sh

cmd="/usr/bin/ssh -TNCL ${rdp_port}:${desktop}:${rdp_port} -p $ssh_portal_port -l is${userid} $ssh_portal"

temp=/tmp/$$.ssh
/bin/bash -c "$cmd" >$temp.1 2>$temp.2 &
tunnel_pid=$!
ret=$?

if [ $ret -ne 0 ]; then
    #/usr/bin/xmessage "ssh tunnel failed" &
    echo -e "'$cmd' failed with error $ret\n\nSTDERR:\n\n$(cat $temp.2)\n\nSTDOUT:\n\n$(cat $temp.1)" | xmessage -file -
    /bin/kill -9 $tunnel_pid
    rm -f $temp.1 $temp.2
    exit 1
fi

/bin/rm -f $temp.1 $temp.2
/bin/sleep 5

temp=/tmp/$$.rdp
/usr/bin/rdesktop -d $domain -u $userid -Pg 1280x800 localhost >$temp.1 \
    2>$temp.2
ret=$?

if [ $ret -ne $rdp_ok -a $ret -ne $rdp_window_closed ]; then
    echo -e "rdesktop failed with error $ret\n\nSTDERR:\n\n$(cat $temp.2)\n\nSTDOUT:\n\n$(cat $temp.1)" | xmessage -file -
fi

/bin/rm -f $temp.1 $temp.2
/bin/kill -9 $tunnel_pid
