#!/usr/bin/env bash

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "ERROR: not enough arguments" 1>&2
    bname=$(basename "$0")
    echo "usage: $bname <session_name>" 1>&2
    exit 1
fi

# session_name=$(echo "$1" | sed -e 's/[^a-zA-Z0-9]/_/g')
session_name=${1//[^a-zA-Z0-9]/_/g}

if [ -z "${TMUX:-}" ]; then
    tmux new-session -As "${session_name}"
else
    current_pane=$(tmux display-message -p "#D")

    if [ "$(tmux list-sessions | grep -c \"^${session_name}:\")" -lt 1 ]; then
        (
            unset TMUX
            tmux new-session -Ad -s "${session_name}"
        )
    fi

    tmux switch-client -t "${session_name}"
    tmux kill-pane -t "${current_pane}"
fi
