#!/usr/bin/env bash

set -euo pipefail

echo ">>> Scanning directories in $(pwd) ..."
find . -type d -maxdepth 1 | while read dir; do
    (
        cd $dir

        if [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]]; then
            session_name=$(basename "$PWD" | sed -e 's/[^a-zA-Z0-9]/_/g')

            if [ -z "$TMUX" ]; then
                tmux new-session -As $session_name
            else
                if [ $(tmux list-sessions | grep "^$session_name:" | wc -l) -lt 1 ]; then
                    echo ">>> Creating tmux session named $session_name"
                    $(unset TMUX; tmux new-session -Ad -s $session_name)
                else
                    echo ">>> Found existing tmux session named $session_name"
                fi
            fi
        fi
    )
done
