#!/usr/bin/env bash

set -Eeuo pipefail

usage() {
    cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS]

Create a new tmux session based on the current working directory.

Options:
    -h      Print this help message and exit
EOF
    exit
}

say() {
    echo -e "### ${1-}" >&2
}

error() {
    say "ERROR: ${1-}"
}

die() {
    error "${1-}"
    exit "${2-1}"
}

parse_opts() {
    while getopts "h" optname; do
        case "${optname}" in
            h)
                usage
                ;;
            \?)
                die "Invalid option: ${OPTARG}"
                ;;
            :)
                die "Invalid option: ${OPTARG} requires an argument"
                ;;
            *)
                break
                ;;
        esac
    done
}

parse_opts "$@"
shift $((OPTIND - 1))

session_name=$(basename "$PWD" | sed -e 's/[^a-zA-Z0-9]/_/g')

if [ -z "${TMUX:-}" ]; then
    tmux new-session -As "${session_name}"
else
    current_pane=$(tmux display-message -p "#D")

    if [ "$(tmux list-sessions | grep -c \"^${session_name}:\")" -lt 1 ]; then
        (
            unset TMUX
            tmux new-session -Ad -s "${session_name}"
        )
    fi

    tmux switch-client -t "${session_name}"
    tmux kill-pane -t "${current_pane}"
fi
