#!/usr/bin/env bash

set -e
set -u

# Create a new tmux session in a provided directory.

if [ $# -lt 1 ]; then
    echo "ERROR: not enough arguments" 1>&2
    echo "usage: $(basename $0) <directory>" 1>&2
    exit 1
fi

directory=$1
test -d $directory || { echo "ERROR: no directory: $directory" 1>&2; exit 1; }

(
    cd $directory
    tmux_new_session_pwd
)
