#!/usr/bin/env bash

set -euo pipefail

if [ -z "${TMUX:-}" ]; then
    if [ $# -lt 1 ]; then
        echo "ERROR: not enough arguments" 1>&2
        bname=$(basename "$0")
        echo "usage: $bname <session_name>" 1>&2
        exit 1
    fi

    tmux kill-session -t "$1"
else
    current_session_name=$(tmux display-message -p '#S')

    if [ "$(tmux ls | grep -c '^general:')" -gt 0 ]; then
        tmux switch-client -t general
    fi

    tmux kill-session -t "$current_session_name"
fi
