#!/usr/bin/env bash

set -euo pipefail

session_name=$(basename "$PWD" | sed -e 's/[^a-zA-Z0-9]/_/g')

if [ -z "${TMUX:-}" ]; then
    tmux new-session -As "${session_name}"
else
    current_pane=$(tmux display-message -p "#D")

    if [ "$(tmux list-sessions | grep -c \"^${session_name}:\")" -lt 1 ]; then
        (
            unset TMUX
            tmux new-session -Ad -s "${session_name}"
        )
    fi

    tmux switch-client -t "${session_name}"
    tmux kill-pane -t "${current_pane}"
fi
