#!/usr/bin/env bash

set -Eeuo pipefail

usage() {
    cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS] [SESSION_NAME]

Kills current tmux session and switch to session named general (if available).
If called inside a tmux session, it will kill the current session. Otherwise,
the session name must be provided.

Options:
    -h      Print this help message and exit
EOF
    exit
}

say() {
    echo -e "### ${1-}" >&2
}

error() {
    say "ERROR: ${1-}"
}

die() {
    error "${1-}"
    exit "${2-1}"
}

parse_opts() {
    while getopts "h" optname; do
        case "${optname}" in
            h)
                usage
                ;;
            \?)
                die "Invalid option: ${OPTARG}"
                ;;
            :)
                die "Invalid option: ${OPTARG} requires an argument"
                ;;
            *)
                break
                ;;
        esac
    done
}

parse_opts "$@"
shift $((OPTIND - 1))

if [[ -z "${TMUX:-}" ]]; then
    if [[ $# -lt 1 ]]; then
        die "Session name not provided"
    fi

    tmux kill-session -t "$1"
else
    current_session_name=$(tmux display-message -p '#S')

    # shellcheck disable=SC2312
    if [[ "$(tmux ls | grep -c '^general:')" -gt 0 ]]; then
        tmux switch-client -t general
    fi

    tmux kill-session -t "${current_session_name}"
fi
