#!/usr/bin/env bash

set -e

(
    echo ">>> cd ~/src/work/trampoline"
    cd ~/src/work/trampoline

    find . -type d -depth 1 | while read dir; do
        echo $(cd $dir; git l | head -1 | awk '{print $2}'; git symbolic-ref HEAD | awk -F/ '{print $3}') $dir
    done
)
