#!/usr/bin/env bash

set -e

(
    echo ">>> cd ~/src/work/trampoline"
    cd ~/src/work/trampoline

    find . -type d -depth 1 | while read dir; do
        (
            cd $dir
            printf "%-15s %-15s %s\n" $(git l | head -1 | awk '{print $2}') $(git symbolic-ref HEAD | awk -F/ '{print $3}') $(basename $(pwd))
        )
    done
)
