#!/usr/bin/env ruby

require 'rubygems'

require 'csv'
require 'etc'
require 'httpclient'
require 'nokogiri'
require 'open-uri'
require 'thor'

# NOTE You'll need to setup Twitter app stuff for the `t` command. See the
# documentation for the `t` command.

# TODO follow all redirects
#   TODO follow bit.ly links
# TODO http://goo.gl/cmiYYE is broken

RCFILENAME = File.join(Etc.getpwuid.dir, '.twlinksrc')
RESULT_LIMIT = 1_000

FILTERS = [
  /imgur\.com/,
  /twitter.*status.*photo/
]

class CLI < Thor
  default_command :get

  desc 'get', 'get all links in tweets since last recorded ID'
  def get
    process_links(get_timeline(build_command))
  end

  desc 'reset', 'reset (remove) the last ID recorded'
  def reset
    File.truncate(RCFILENAME, 0) if File.exist?(RCFILENAME)
  end

  private

  # FIXME previous_id is off by one sometimes.
  def build_command
    command = "command t timeline -c -n #{ RESULT_LIMIT }"
    previous_id = File.exist?(RCFILENAME) ? File.read(RCFILENAME).to_i : 0
    command << " -s #{ (previous_id + 1) }" if previous_id > 0
    # command << " 2> /dev/null"
    command
  end

  def get_timeline(command)
    timeline = CSV.parse(%x{#{ command }})
    timeline.shift # remove CSV headers
    timeline
  end

  def process_links(timeline)
    unless timeline.empty?
      save_new_id(get_new_id(timeline))
      display_links(timeline)
    end
  end

  def get_new_id(timeline)
    timeline.first(2).last.first
  end

  def save_new_id(new_id)
    File.open(RCFILENAME, 'w') { |f| f.write("#{ new_id }\n") }
  end

  def display_links(timeline)
    timeline.each do |tweet|
      link = get_link(tweet)
      if link
        redirect_link = get_redirect_link(link)
        if redirect_link && !filtered?(redirect_link)
          printf("%s => %s\n\t%s\n\n",
                 get_screename(tweet),
                 get_title(redirect_link),
                 redirect_link)
        end
      end
    end
  end

  def get_link(tweet)
    /(http\S+)/.match(tweet.last).to_a.first
  end

  def get_screename(tweet)
    tweet[-2]
  end

  def get_title(link)
    title = Nokogiri::HTML(HTTPClient.new.get(link).body).css('head title').inner_text
    title.to_s.empty? ? '[no title]' : title.strip
  rescue => error
    "[error getting page title on #{ link }: #{ error }]"
  end

  def get_redirect_link(link)
    HTTPClient.new.head(link).header['Location'].first # or use #get
  rescue => error
    warn "[error getting redirect link on #{ link }: #{ error }]"
    nil
  end

  def filtered?(link)
    FILTERS.any? { |filter| filter.match(link) }
  end
end

CLI.start(ARGV) if $0 == __FILE__
