#!/usr/bin/env bash

# Uninstall a package previously installed with pip, and uninstall all of that
# package's dependencies too (since `pip uninstall` doesn't do that).

set -euo pipefail

if [ $# -lt 1 ]; then
    >&2 echo "ERROR: no package specified"
    exit 1
fi

pkg=$1

for dep in $(pip show "$pkg" | grep Requires | sed 's/Requires: //g; s/,//g') ; do
    pip uninstall -y "$dep"
done

pip uninstall -y "$pkg"
