#!/bin/sh

# Verify the bom exists, otherwise don't do anything
[ -e /var/db/receipts/org.nodejs.pkg.bom ] || {
  echo 'Nothing to do.'
  exit 0
}

# Loop through all the files in the bom.
lsbom -f -l -s -pf /var/db/receipts/org.nodejs.pkg.bom \
| while read i; do
  # Remove each file listed in the bom.
  rm /usr/local/${i}
done

# Remove directories related to node.js.
rm -rf /usr/local/lib/node \
  /usr/local/lib/node_modules \
  /var/db/receipts/org.nodejs.*

exit 0
