#!/usr/bin/env bash

# set -euo pipefail

if command -v pyenv 1>/dev/null 2>&1; then
    # Requires pyenv-update plugin.
    echo
    echo "### Updating with pyenv ..."
    echo
    pyenv update
fi

if command -v pip 1>/dev/null 2>&1; then
    echo
    echo "### Updating with pip ..."
    echo
    pip install --upgrade pip
fi

if command -v nodenv 1>/dev/null 2>&1; then
    # Requires nodenv-update plugin.
    echo
    echo "### Updating with nodenv ..."
    echo
    nodenv update
fi

if command -v npm 1>/dev/null 2>&1; then
    echo
    echo "### Updating with npm ..."
    echo
    npm install --global npm
fi

if command -v goenv 1>/dev/null 2>&1; then
    echo
    echo "### Updating with goenv ..."
    echo
    (
        cd "$(goenv root)" || return
        git pull
    )
fi
