#!/usr/bin/env bash

set -e

echo ">>> Loading GitHub SSH key"

keychain --nogui ~/.ssh/id_dsa_github.pub && source ~/.keychain/$(hostname)-sh

echo ">>> Updating Vim ..."
echo

(
    cd ~/src/rcfiles
    git submodule foreach git pull -q origin master
)

echo
