#!/usr/bin/env bash

set -euo pipefail

dirty_check_git

echo ">>> Updating Git from thumbdrive ..."
echo

thumbdrive_directory=/Volumes/thumbdrive

if [ ! -d $thumbdrive_directory ]; then
    echo ">>> No thumbdrive mounted. Skipping update."
    echo
    exit 0
fi

(
    if [ ! "$SKIP_THUMBDRIVE_REMOUNT" ]; then
        echo ">>> Re-mounting thumbdrive"
        diskutil unmount thumbdrive && mkdir /Volumes/thumbdrive && sudo mount -t hfs /dev/disk2s2 /Volumes/thumbdrive
    fi

    cd

    for directory in bin doc/* src/rcfiles src/personal/*; do
        thumbdrive_subdirectory=$thumbdrive_directory/pete/$directory
        home_subdirectory=$HOME/$directory

        if [[ ! -d $thumbdrive_subdirectory ]]; then
            mkdir -p "$thumbdrive_subdirectory"
        fi

        if [[ -d $thumbdrive_subdirectory ]]; then
            echo ">>> Updating $thumbdrive_subdirectory"
            cd "$thumbdrive_subdirectory"

            if [ ! -d .git ]; then
                git init
            fi;

            git gc --auto
            git pull "$home_subdirectory"
            echo
        fi

        if [[ -d $home_subdirectory ]]; then
            echo ">>> Updating $home_subdirectory"
            cd "$home_subdirectory"
            # git gc --auto
            git pull "$thumbdrive_subdirectory"

            if [ -e .gitmodules ]; then
                git submodule init
                git submodule update
            fi

            echo
        fi
    done

    echo ">>> Unmounting thumbdrive"
    cd && diskutil unmount thumbdrive

    echo
)
