#!/usr/bin/env bash

set -euo pipefail

echo "### Updating nodenv ..."
nodenv update

echo "### Updating npm and yarn ..."
npm install --global npm
npm install --global yarn

echo "### Updating pyenv ..."
pyenv update

echo "### Updating pip ..."
pip install --upgrade pip

echo "### Updating rbenv ..."
rbenv update

echo "### Updating rubygems ..."
gem update --system --no-document
