#!/usr/bin/env bash

set -e

dirty_check_git

export SKIP_THUMBDRIVE_REMOUNT=true
update_git_work

echo ">>> Updating Git from remote ..."
echo

(
    for directory in $HOME/bin $HOME/doc/* $HOME/src/rcfiles $HOME/src/personal/*; do
        if [[ -d $directory ]]; then
            if [ $(git remote -v | grep "origin" | wc -l) -gt 0 ]; then
                echo ">>> Updating $directory"
                cd $directory
                git gc --auto
                git pull

                if [ -e .gitmodules ]; then
                    git submodule init
                    git submodule update
                fi

                git push
                echo
            fi
        fi
    done
)
