#!/usr/bin/env bash

set -e

echo ">>> Loading GitHub SSH key"

keychain --nogui ~/.ssh/id_dsa_github.pub && source ~/.keychain/$(hostname)-sh

dir=~/src/personal/github/dotfiles
echo ">>> Updating Vim: ${dir}"
echo

(
    cd ${dir}
    git submodule foreach git pull -q origin master
)

echo
