#!/usr/bin/env bash

set -euo pipefail

echo
echo "### Updating pyenv ..."
echo
pyenv update

echo
echo "### Updating pip ..."
echo
pip install --upgrade pip

echo
echo "### Updating nodenv ..."
echo
nodenv update

echo
echo "### Updating npm ..."
echo
npm install --global npm

echo
echo "### Updating goenv ..."
echo
(
    cd "$(goenv root)"
    git pull
)

echo
echo "### Updating rust ..."
echo
rustup update
