#!/usr/bin/env bash

set -e

{
    cd ~/src/rcfiles
    tar cf ~/tmp/vim.tar vim/*

    for host in cuatro devhost pike; do
        echo ">>> $host"
        scp ~/tmp/vim.tar $host:
        ssh $host 'rm -r .vim && tar xf vim.tar && mv vim .vim && rm vim.tar'
        echo
    done

    rm ~/tmp/vim.tar
}
