#!/usr/bin/env perl

# Pipe stdout of "sudo vgptool rsop" into this program to see the sudo rights
# applied to the system it's run on.

use strict;
use warnings;

my $print = 0;

while (<>) {
    if (/^\s*CSE:/) {
        $print = /vgp_sudoext/ ? 1 : 0;
        next;
    }

    if ($print) {
        next if /^\s*--/;
        next if /^\s*Policy/;
        next if /^\s*$/;
        print;
    }
}
