#!/usr/bin/env bash

# Run a command when files in given directories change.
# Usage: $(basename "$0") [-h] <dir> [<dir> ...] -- <command> [arg ...]

set -Eeuo pipefail

dirs=()

until [[ $1 == "--" ]]; do
	dirs+=("$1")
	shift
done

shift

rest=("$@")

if command -v inotifywait 1>/dev/null 2>&1; then
	inotifywait -rm -e create -e modify -e moved_to --format '%w%f' "${dirs[@]}" | \
		while read -r filename; do
			if [ -f "${filename}" ]; then
				echo "### Running command for file: ${filename}"
				"${rest[@]}" "$filename"
			fi
		done
else
	echo "### ERROR: inotifywait not found" >&2
	exit 1
fi
