#!/usr/bin/env bash

set -e

today=$(date '+%d%m%Y')

rm -rf ~/tmp/online_source_code*
mkdir -p ~/tmp/online_source_code

(
    cd ~/src/work
    git_pull_list
)

cat ~/src/work/list | egrep -iv 'pinnacol-www|return-to-work|onlineapps' | while read dir; do
    echo ">>> $dir"
    mkdir -p ~/tmp/online_source_code/${dir}

    (
        cd ~/src/work/${dir}
        git checkout-index -f -a --prefix=/Users/${USER}/tmp/online_source_code/${dir}/
    )

    echo
done

(
    cd ~/tmp
    zip -r online_source_code_${today}.zip online_source_code
)
